<?php

/**
 * @file
 * An API module that allows easy integration with the Eloqua automated
 * marketing platform.
 *
 * NOTE: Out of the box, this will almost certainly not do what you want it to.
 * Please see README.txt for custom integration details.
 */


define('ELOQUA_API_DEFAULT_POST_URL', 'http://now.eloqua.com/e/f2.aspx');
define('ELOQUA_API_DEFAULT_SITE_ID', -1);
define('ELOQUA_API_DEFAULT_LOG', TRUE);
define('ELOQUA_API_DEFAULT_EXPLICIT_VALUES', TRUE);
define('ELOQUA_API_DEFAULT_TIMEOUT', 10);
define('ELOQUA_API_DEFAULT_TRACKING_ENABLED', 0);
define('ELOQUA_API_DEFAULT_TRACKING_PATH', 'sites/all/libraries/elqNow');
define('ELOQUA_API_DEFAULT_SEND_CUSTOMER_GUID', 0);
define('ELOQUA_API_DEFAULT_CUSTOMER_GUID_FIELD', 'elqCustomerGUID');
define('ELOQUA_API_DEFAULT_COOKIE_WRITE_FIELD', 'elqCookieWrite');


/**
 * Implements hook_permission().
 */
function eloqua_api_permission() {
  return array(
    'administer eloqua api' => array(
      'title' => t('Administer Eloqua API Configurations'),
    ),
  );
}


/**
 * Implements hook_menu().
 */
function eloqua_api_menu() {
  $items = array();

  // Administration page.
  $items['admin/config/services/eloqua-api/settings'] = array(
    'title' => 'Eloqua API',
    'description' => 'Configure Eloqua integration options.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('eloqua_api_admin_settings'),
    'access arguments' => array('administer eloqua api'),
    'file' => 'eloqua_api.admin.inc',
  );

  return $items;
}


/**
 * Implements hook_preprocess_HOOK().
 */
function eloqua_api_preprocess_html(&$variables) {
  $settings = _eloqua_api_get_settings();
  if ($settings['tracking_enabled']) {
    $path = _eloqua_api_tracking_path() . '/';
    $options = array(
      'type' => 'file',
      'scope' => 'footer',
    );
    drupal_add_js($path . 'tracking.js', $options);
  }
}


/**
 * Implements hook_form_alter().
 */
function eloqua_api_form_alter(&$form, &$form_state, $form_id) {
  $settings = _eloqua_api_get_settings();

  // If this form is enabled, add our submit handler.
  if (isset($settings['enabled_forms'][$form_id]) && $settings['enabled_forms'][$form_id]) {
    $form['#validate'][] = 'eloqua_api_validate';
    $form['#submit'][] = 'eloqua_api_submit';

    // If we're using explicit values, be sure to set the array.
    if ($settings['explicit_values'] && !isset($form_state['eloqua_values'])) {
      $form_state['eloqua_values'] = array();
    }

    // If configured to do so, add JS and hidden field for GUID.
    if ($settings['send_customer_guid']) {
      // Attach the JavaScript.
      $modpath = drupal_get_path('module', 'eloqua_api');
      $form['#attached']['js'][] = $modpath . '/js/form_attachment.js';

      // Create a hidden field with ID to attach to.
      $form['eloqua_api_cid'] = array(
        '#type' => 'hidden',
        '#attributes' => array('id' => 'eloqua-api-cid'),
      );
    }
  }
}


/**
 * Generic validation handler for Eloqua enabled forms.
 *
 * Custom fields provided by this module are mapped here.
 */
function eloqua_api_validate($form, &$form_state) {
  // Determine whether we're writing to "eloqua_values" or "values."
  $settings = _eloqua_api_get_settings();
  $append = &$form_state[($settings['explicit_values'] ? 'eloqua_values' : 'values')];

  // If configured, get and append the customer GUID.
  if ($settings['send_customer_guid'] && isset($form_state['values']['eloqua_api_cid'])) {
    $append[$settings['customer_guid_field']] = $form_state['values']['eloqua_api_cid'];
    $append[$settings['cookie_write_field']] = '0';
    unset($form_state['values']['eloqua_api_cid']);
  }
}


/**
 * Generic submit handler for Eloqua enabled forms.
 *
 * All this does is submit all values attached to the form to Eloqua. It's your
 * responsibility to make sure that all fields are present and map to the right
 * values within Eloqua by form altering and adding them via your own validation
 * function(s).
 */
function eloqua_api_submit($form, &$form_state) {
  $settings = _eloqua_api_get_settings();

  if ($settings['explicit_values']) {
    eloqua_api_post($form_state['eloqua_values'], $settings['post_url']);
  }
  else {
    eloqua_api_post($form_state['values'], $settings['post_url']);
  }
}


/**
 * Posts a series of parameters to Eloqua asynchronously.
 *
 * @param array $params
 *   An array of parameters (keyed by name) to pass to Eloqua.
 *
 * @param string $url
 *   The URL to which params will be POST'ed, defaults to the specified script.
 */
function eloqua_api_post($params = array(), $url = NULL) {
  $settings = _eloqua_api_get_settings();

  // Only POST the form if a site ID is set.
  if ($settings['site_id'] > 0) {
    // Don't post an empty form.
    if (!empty($params)) {
      // Append default information.
      $params += array(
        'elqSiteID' => $settings['site_id'],
      );

      // Assign the default URL if none is provided.
      if (empty($url)) {
        $url = $settings['post_url'];
      }

      // Create a query string from the parameters.
      $post_string = http_build_query($params);
      $url_parts = parse_url($url);

      // Pull out the useful path parts.
      $host = $url_parts['host'];
      $path = $url_parts['path'];
      $port = isset($url_parts['port']) ? $url_parts['port'] : 80;

      // Set up our POST request.
      $out = "POST " . $path . " HTTP/1.1\r\n";
      $out .= "Host: " . $host . "\r\n";
      $out .= "Content-Type: application/x-www-form-urlencoded\r\n";
      $out .= "Content-Length: " . strlen($post_string) . "\r\n";
      $out .= "Connection: Close\r\n\r\n";

      // Append POST data.
      $out .= $post_string;

      // Open the socket, POST, then close the socket.
      if (!variable_get('eloqua_api_skip_post', FALSE)) {
        $fp = fsockopen($host, $port, $errno, $errstr, $settings['timeout']);

        // Log any errors that occurred.
        if (!$fp) {
          watchdog('eloqua api', 'Eloqua post failed: error opening the socket. <br /><br /> @message', array('@message' => $errstr), WATCHDOG_ERROR);
        }
        else {
          fwrite($fp, $out);
          fclose($fp);
        }
      }

      // Log the POST.
      if ($settings['log']) {
        $sanitized_out = filter_xss(nl2br($out), array('br'));
        watchdog('eloqua api', 'Eloqua post successful: <br /><br /> !post', array('!post' => $sanitized_out), WATCHDOG_NOTICE);
      }
    }
    else {
      watchdog('eloqua api', 'Eloqua post aborted: no parameters passed.', array(), WATCHDOG_WARNING);
    }
  }
  else {
    watchdog('eloqua api', 'Eloqua post failed: no Site ID provided.', array(), WATCHDOG_ERROR);
  }
}


/**
 * Returns Eloqua API settings.
 *
 * @param boolean $refresh
 *   Whether or not to pull settings freshly. Defaults to FALSE.
 *
 * @return array
 *   An array of Eloqua API settings, keyed by name.
 */
function _eloqua_api_get_settings($refresh = FALSE) {
  static $settings;

  // All variables defined by the module.
  $field_keys = array(
    'post_url',
    'site_id',
    'log',
    'explicit_values',
    'timeout',
    'tracking_enabled',
    'send_customer_guid',
    'customer_guid_field',
    'cookie_write_field',
  );

  // Loop through each field and return its default.
  if ($refresh || empty($settings)) {
    foreach ($field_keys as $field) {
      $settings[$field] = variable_get(
        'eloqua_api_' . $field,
        constant('ELOQUA_API_DEFAULT_' . strtoupper($field))
      );
    }
  }

  $settings['enabled_forms'] = variable_get('eloqua_api_enabled_forms', array());

  return $settings;
}


/**
 * Return the path to Eloqua tracking scripts.
 */
function _eloqua_api_tracking_path() {
  static $library_path = NULL;

  // Try to locate the library path in any possible setup.
  if ($library_path == NULL) {
    // Ask the libraries module.
    if ($library_path == NULL && module_exists('libraries')) {
      if ($path = libraries_get_path('elqNow')) {
        $library_path = $path;
      }
    }
    // If no path is found suggest the default one.
    elseif ($library_path == NULL) {
      $library_path = ELOQUA_API_DEFAULT_TRACKING_PATH;
    }
  }

  return $library_path;
}
